experiment_name: experiment_1

test: true
csv_path: "./dataset/pokedex.csv"
images_dir: "./dataset/images"

image_size: 128
num_epochs: 500
batch_size: 64
num_workers: 16

encoder_type: "clip"

up_type: "nearest"

use_spectral_norm: true
down_type: "stride_conv"

lr_G: 0.0001
lr_D: 0.0004
lr_text: 0.00002
